---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
---
spring:
  profiles: prod,local,default
datasource:
  sampleapp:
    url: jdbc:oracle:thin:@localhost:1521:ORACLEDB
    username: SYSTEM
    password: admin
    driverClassName: oracle.jdbc.driver.OracleDriver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect